name: Release Manager

on:
  workflow_dispatch:
    inputs:
      backend_bump:
        description: 'Backend version bump (patch/minor/major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      frontend_bump:
        description: 'Frontend version bump (patch/minor/major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      platform_bump:
        description: 'Platform version bump (patch/minor/major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  update-release-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update release config
        run: |
          echo "{
            \"backend\": \"${{ github.event.inputs.backend_bump }}\",
            \"frontend\": \"${{ github.event.inputs.frontend_bump }}\",
            \"platform\": \"${{ github.event.inputs.platform_bump }}\"
          }" > release_config.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update release bumps: backend=${{ github.event.inputs.backend_bump }}, frontend=${{ github.event.inputs.frontend_bump }}, platform=${{ github.event.inputs.platform_bump }}"
          title: "Release Bump: ${{ github.event.inputs.backend_bump }}/${{ github.event.inputs.frontend_bump }}/${{ github.event.inputs.platform_bump }}"
          body: |
            ## Release Version Bumps
            
            - **Backend**: ${{ github.event.inputs.backend_bump }}
            - **Frontend**: ${{ github.event.inputs.frontend_bump }}
            - **Platform**: ${{ github.event.inputs.platform_bump }}
            
            This PR updates the release configuration with the selected version bumps.
          branch: release-bump-${{ github.run_number }}
          delete-branch: true
